### ISSUE TITLE
Unavailable on galaxy?

### ISSUE THREAD

**Issue by PaulMougel** [weareinteractive/ansible-pm2#10]
Thank you for making this role available :+1: 

It looks like it isn't available on galaxy: https://galaxy.ansible.com/weareinteractive/pm2/ returns 404. https://galaxy.ansible.com/franklinkim/pm2/ is available (up to v1.3 though).

Note that I was able to install the role using:
```sh
ansible-galaxy install https://github.com/weareinteractive/ansible-pm2/archive/2.0.0.tar.gz -p /etc/ansible/roles/weareinteractive.pm2
```
and by including it using:
```yml
- name: testing ansible and pm2
  hosts: all
  become: yes
  roles:
    - weareinteractive.pm2/2.0.0
```

However that doesn't feel right… am I missing something?
