### ISSUE TITLE
adding node_args

### ISSUE THREAD

**Issue by codereviewvideos** [weareinteractive/ansible-pm2#15]
Hi, 

Firstly, thank you very much for creating and maintaining this role, it has saved me a lot of time.

One thing I'm unsure on is whether there is out of the box support for `node_args` - http://pm2.keymetrics.io/docs/usage/application-declaration/#attributes-available

I added config along the lines of:

```
pm2_apps:
  - run: "my-script.js"
    args: "--watch -i max"
    node_args: "--harmony-async-await"
    path: "/path/to/my/src"
    env:
      NODE_ENV: dev
```

As I wanted to use async / await.

This doesn't work directly. 

I have managed to make this work by changing `manage.yml` to :

```
- name: Starting apps
  environment: "{{ item.env | default({}) }}"
  shell: "pm2 start {{ item.run }} {{ item.args | default() }} {{ '--node-args=' + item.node_args if item.node_args is defined else '' }}"
```

It's not pretty, but it works. 

I'm open to a nicer implementation, or learning the correct way to do this. If not, is this something you would consider merging if I put together a PR ? 

Thanks

Chris

**Comment by franklinkim** [comment]
hi,  actually, it should be possible to just append it to `args` since it's just a string I'm appending to the command... have you tried sth like:

```yaml
pm2_apps:
  - run: "my-script.js"
    args: "--watch -i max --node-args=--harmony-async-await"
    path: "/path/to/my/src"
    env:
      NODE_ENV: dev
```
