### ISSUE TITLE
Cannot set property console of #<Object> which only has a getter

### ISSUE THREAD

**Issue by szarapka** [weareinteractive/ansible-pm2#2]
Just started setting up my playbook and ran into this:

```
PLAY [Setup PM2] **************************************************************

GATHERING FACTS ***************************************************************
ok: [10.0.0.0]

TASK: [franklinkim.nodejs | Installing packages] ******************************
ok: [10.0.0.0] => (item=nodejs)

TASK: [franklinkim.nodejs | Installing packages] ******************************
skipping: [10.0.0.0]

TASK: [franklinkim.nodejs | Updating global packages] *************************
skipping: [10.0.0.0]

TASK: [franklinkim.pm2 | Install packages] ************************************
changed: [10.0.0.0] => (item=pm2)

TASK: [franklinkim.pm2 | installing startup script] ***************************
failed: [10.0.0.0] => {"changed": true, "cmd": ["pm2", "-s", "startup", "ubuntu"], "delta": "0:00:00.220626", "end": "2014-12-02 03:32:09.602987", "rc": 8, "start": "2014-12-02 03:32:09.382361"}
stderr:
/usr/lib/node_modules/pm2/bin/pm2:83
  global.console = {};
                 ^
TypeError: Cannot set property console of #<Object> which has only a getter
    at Object.<anonymous> (/usr/lib/node_modules/pm2/bin/pm2:83:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

FATAL: all hosts have already failed -- aborting
```

This is what my playbook looks like:

```

---
# This playbook deploys a web application server.

- name: Apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: Setup PM2
  hosts: all
  remote_user: root
  vars:
    pm2_startup: ubuntu
    pm2_apps:
      - /var/www/appname/pm2.json

  roles:
    - franklinkim.pm2
```

Any ideas?
