### ISSUE TITLE
Bug: Job for pm2-USERNAME.service failed because the service did not take the steps required by its unit configuration

### ISSUE THREAD

**Issue by favoyang** [weareinteractive/ansible-pm2#26]
#### Issues

The pm2 role fails on the initial setup on Ubuntu 18.04, and reports:
```
Bug: Job for pm2-USERNAME.service failed because the service did not take the steps required by its unit configuration
```

The issue is self-fixed after a restart.

#### Step to reproduce

OS: Ubuntu 18.04

Server name: webserver

User: webrunner 

Ansible playbook:
```
  - name: Start pm2
    import_role:
      name: weareinteractive.pm2
    vars:
      pm2_user: webrunner
      pm2_service_name: pm2-webrunner
      pm2_apps:
        - run: pm2-webrunner.yml
          path: /srv/webrunner
          cmd: startOrGracefulReload
          env:
            NODE_ENV: production
      pm2_post_cmds:
        - run: save
          path: /srv/webrunner
          env:
            NODE_ENV: production
```

Logs:
```
TASK [weareinteractive.pm2 : Install packages] ********************************************************************************************************
ok: [webserver]

TASK [weareinteractive.pm2 : Looking up user home] ****************************************************************************************************
ok: [webserver]

TASK [weareinteractive.pm2 : Installing startup script] ***********************************************************************************************
changed: [webserver]

TASK [weareinteractive.pm2 : Executing commands] ******************************************************************************************************
changed: [webserver] => (item={u'path': u'/srv/webrunner', u'run': u'save', u'env': {u'NODE_ENV': u'production'}})

TASK [weareinteractive.pm2 : Managing apps] ***********************************************************************************************************
changed: [webserver] => (item={u'path': u'/srv/webrunner', u'cmd': u'startOrGracefulReload', u'run': u'pm2-webrunner.yml', u'env': {u'NODE_ENV': u'production'}})

TASK [weareinteractive.pm2 : Executing post commands] *************************************************************************************************

TASK [weareinteractive.pm2 : Configuring service] *****************************************************************************************************
fatal: [webserver]: FAILED! => {"changed": false, "msg": "Unable to start service pm2-webrunner: Job for pm2-webrunner.service failed because the service did not take the steps required by its unit configuration.\nSee \"systemctl status pm2-webrunner.service\" and \"journalctl -xe\" for details.\n"}
```

#### Why it happens?

The role executes follow sub-tasks by order:
1. install.yml which creates the startup script
2. manage.yml which starts the pm2 process
3. service.yml which starts the service

The problem is that the pm2 main process needs to be managed by systemd. But it's been already started by the user in step 2.

The workaround,
- run `pm2 kill` to stop the pm2 main process.
- run `sudo service pm2-USERNAME start` to start a managed pm2 main process.
- then it works.

Restart the server also fix it, because the systemd launched the pm2 main process for you.

#### How to fix it?

Start the pm2-USERNAME service before running any commands in the manage.yml. Basically, move service.yml before manage.yml.
